import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    // Legacy UI surfaces still contain explicit `any` annotations that are
    // already constrained by the blocking TypeScript gate. Keep them visible
    // as lint warnings while the final adversarial pass removes the remaining
    // typing debt; all other ESLint errors remain blocking.
    rules: {
      "@typescript-eslint/no-explicit-any": "warn",
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the PWA build; lint source, not generated service-worker output.
    "public/swe-worker-*.js",
  ]),
]);

export default eslintConfig;
